### ISSUE TITLE
Tiles don't load when editing using Safari 9.0.x

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#2913]
I'm using Safari 9.0.2 and when I start editing, or edit from the HOT Tasking Manager, the imagery tiles don't load sometimes, it just is black. I'm using Mac OS X Yosemite.

And when I zoom in with the pink HOT Tasking Manager box it appears to zoom in, but then it seems to zoom out and nothing shows up. Not sure how to do gif screen capture but here's what it looks like.

The tiles seem to show up when I refresh, but if I'm using the Tasking Manager refreshing makes the pink box delineating the tile go away.

![screen shot 2016-01-13 at 2 39 30 pm](https://cloud.githubusercontent.com/assets/5025092/12305575/7c03618e-ba03-11e5-98f4-742ecab64f75.png)

**Comment by bhousel** [comment]
Yeah, we've seen this before with #2614.
Sometimes the custom imagery on http://hiu-maps.net doesn't load correctly.  The requests return an OK status but black tiles.

There is supposed to be a step in the tasking manager where you accept a license for the imagery, and I think that might be the key to getting it to load.  After you accept the license, I think it must store your information someplace and the requests will succeed.  

Another possibility: I just now tried it, and zooming out and then back in seemed to help.  So it's possible that the task starts you off in a zoom level where the imagery needs to be overzoomed to work.

**Comment by aawiseman** [comment]
Ah, ok. This was the task I was using: http://tasks.hotosm.org/project/1082#task/235

It didn't ask me for the license, maybe I accepted it in the past so it skipped that?

**Comment by aawiseman** [comment]
Actually, it looks like it does it with a non-HIU imagery task too: http://tasks.hotosm.org/project/1423#task/264

This one my browser gave me an error that the tab wasn't responding and needed to be reloaded.

**Comment by aawiseman** [comment]
Doh

**Comment by aawiseman** [comment]
I just tried again and got this message: "This editor is supported in Firefox, Chrome, Safari, Opera, and Internet Explorer 11 and above. Please upgrade your browser or use Potlatch 2 to edit the map."

**Comment by bhousel** [comment]
> I just tried again and got this message: "This editor is supported in Firefox, Chrome, Safari, Opera, and Internet Explorer 11 and above. Please upgrade your browser or use Potlatch 2 to edit the map."

That's not happening for me right now, but an iD update did just get pushed out an hour ago.  You got that message when clicking on a HOT task to edit?

**Comment by aawiseman** [comment]
I got it when I clicked "edit with iD editor" for the task, after selecting it. 

I just tried again, got the same weird effect where when you zoom in, it seems to zoom in then seems to zoom out again, and the imagery tiles go away so the screen is black. Here's what happened when I first clicked "edit with iD editor" just now, and then it was just black after I zoomed in.

What's odd is when I hid my favorites, the imagery came back and it works fine (second picture)
![screen shot 2016-01-20 at 11 28 45 am](https://cloud.githubusercontent.com/assets/5025092/12455315/17c653d2-bf69-11e5-89d9-e33c46416f50.png)
![screen shot 2016-01-20 at 11 26 35 am](https://cloud.githubusercontent.com/assets/5025092/12455316/17ce97fe-bf69-11e5-874c-ea416eab4025.png)

**Comment by bhousel** [comment]
I still don't know what's causing this issue but it really just seems like an issue with Safari.

I have noticed that toggling on the minimap (key '/') seems to help.

**Comment by aawiseman** [comment]
@bhousel hm interesting, I'll try that.

Anybody else want to look into this? I don't really know any coding stuff to help sadly.

**Comment by bhousel** [comment]
> Anybody else want to look into this? I don't really know any coding stuff to help sadly.

Next step is I am going to try to make a minimal test case and learn exactly what is causing the rendering issue, and maybe submit to webkit team if it's something only they can solve.

**Comment by bhousel** [comment]
Good news!

I made a test case here:  http://sonny.7thposition.com/osm/iD/#map=17.76/18.53595/4.33465 with the custom imagery and gpx removed, and loaded from http to avoid mixed content warnings.  iD crashes almost immediately if you visit that url with Safari 9.

After checking the stack trace in the crash reporting log (`~/Library/Logs/DiagnosticReports/`), I think we're hitting [this webkit bug](https://bugs.webkit.org/show_bug.cgi?id=149613), and it looks like it was fixed just last week in [this changeset](http://trac.webkit.org/changeset/195411).

I also confirm that this crash isn't occurring in the current Webkit nightly build, so it looks like their fix solved the issue.

And in case anyone is wondering when this webkit fix will make it into a new version of Safari... "Apple does not comment on future releases of Safari, their timing, nor their contents."  ¯\\\_(ツ)_/¯

**Comment by aawiseman** [comment]
Awesome, thanks!

**Comment by bhousel** [comment]
So weird:   Apple has pushed out Safari 9.1 and the bug is still there.  And I can see that it's present in Webkit nightly too.  Both Safari 9.1 and Webkit nightly show "AppleWebKit/601.5.17" in the userAgent string, although I would expect Webkit nightly to be ahead of Safari's version.   So I don't know whether they fixed it and then broke it again, or they only fixed part of it, or maybe I am testing wrong.  

I was hoping to close this, but unfortunately need to do more investigation..

**Comment by bhousel** [comment]
test case: https://openstreetmap.us/iD/master/#background=custom:http://hiu-maps.net/hot/1.0.0/bangui-25mar2014-flipped/{z}/{x}/{y}.png&map=15.15/18.5358/4.3331

**Comment by aawiseman** [comment]
Still having this issue, I'm on Safari 9.1.1 -- any idea what might be causing it? Even if it's on Safari's side.

**Comment by bhousel** [comment]
Hey @aawiseman, I just upgraded to macOS Sierra today and it looks like this issue might be fixed in Safari 10.  Can you try it out and let me know what you find?  Thanks!

**Comment by bhousel** [comment]
Closing here, as it seems fixed in Safari 10.
