### ISSUE TITLE
Don't offer leisure=park for nodes

### ISSUE THREAD

**Issue by kleidt** [openstreetmap/iD#2974]
According to the wiki, `leisure=park` should not be used on nodes (only on closed ways).
In fact it is used today over 55'000 times on nodes. But if you take a closer look at these nodes, you will find typical patterns (I found them a lot during #MapLesotho, you find them easily with overpass):
`leisure=park` for mapping a single tree.
`leisure=park` & `natural=tree` for mapping a single tree.
`leisure=park` & `name=tree` for mapping a single tree.

Most of them are created with ID, so I take a closer look at this. I found the following (misleading) behaviour:
- Start editing with ID.
- Set a new node.
- On the left side appears potential tags. The top key is **park** and the icon shows a **tree**.
- this adds a **node** with `leisure=park`
- Because these "trees" are not rendered, some mappers start to add additional tags like `natural=tree` or `name=tree` to get something shown on map.

Please remove `park` from node option.
You may add `natural=tree` instead for nodes, as the mappers actually use this ID feature for.

**Comment by bhousel** [comment]
I think you found a mistake on the wiki.  The [`leisure=*`](https://wiki.openstreetmap.org/wiki/Key:leisure) page says that this tag is acceptable for both nodes or areas, but the [`leisure=park`](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpark) page has the node icon crossed out, yet says "You might possibly mark a very small park with a node, but even for small parks it is more useful to draw in an area."

**Comment by kleidt** [comment]
The problem is, that nearly all of the cases where I check leisure=park on a node this POI was used to map a single tree. And this is definitely wrong!
See [Overpass query](http://overpass-turbo.eu/s/efR) which results in over 2000 nodes, which are  	probably all wrong mappings caused by the misleading behaviour of ID. If this is the reason for over 50'000 wrong mapped trees in the world, maybe ID should remove this option or add natural=tree as an alternative or warn about leisure=park without a name or find a different solution.

But if an editor preset is responsible for tenth of thousands of mapping error, this should be fixed in the editor - in my opinion.

**Comment by bhousel** [comment]
I looked at that overpass query, but as far as I can tell most of those nodes were added by a user named GeoFrizz as part of "`#maplesotho rural task #2`", and they used "`JOSM/1.5 (8757 en)`" as their editor.

We don't even have a preset in iD that looks like `leisure=park + natural=tree`

**Comment by bhousel** [comment]
<img width="327" alt="screenshot 2016-02-07 13 04 00" src="https://cloud.githubusercontent.com/assets/38784/12874135/ba7c7b0c-cd9b-11e5-8d91-8cc6db01b458.png">

**Comment by kleidt** [comment]
Please take a closer lock at the data (history):
This changeset has no new nodes. But GeoFrizz adds in 1395 cases a natural=tree= to an existing leisure=park. Please look at the original nodes (v1):
node | user | editor
3742794422 | Fifi1984 | iD 1.7.3
3723831586 | nkarengmothibe | iD 1.7.3
3697891057 | Ts'epo | iD 1.7.3
3697493390 | ntebo | iD 1.7.3
3671509148 | makhauta | iD 1.7.3
...
only a few samples I randomly took. And these nodes are only in the changeset you mention!
Around Zürich, I found 8 trees mapped this way by 3 different users.

**Comment by bhousel** [comment]
I'm still not changing what iD does.  Our "Park" preset is perfectly clear.

But I guess you can read more about the #MapLesotho initiative here: https://maplesotho.wordpress.com/ 

Please consider:
* The "Park" preset may not be translated very well into the mapper's native language
* There was a contest, so people might have been a bit careless in mapping in order to boost their ranking
* These task tiles were supposedly "validated" by mappers who should know the correct preset.
* A skilled JOSM user can just select all this stuff and fix it quickly  (Look at how efficiently GeoFizz was able to add `natural=tree` to each node - an incorrect thing to do, but whatever).
