### ISSUE TITLE
'?' zooms instead of opening the keyboard shortcuts screen on Swedish keyboard

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4079]
from https://github.com/openstreetmap/iD/pull/3791#issuecomment-305776324

It zooms because on the Swedish (and maybe others) keyboard, <kbd>?</kbd> is <kbd>⇧+</kbd>

**Comment by bhousel** [comment]
@magol, can you test this fix in http://preview.ideditor.com/master ?
Thanks!

**Comment by magol** [comment]
@bhousel Unfortunately it still does not work.
It behaves in exactly the same way as before.

**Comment by bhousel** [comment]
@magol Sorry, I'll reopen and hopefully someone with a keyboard like that can debug!

**Comment by manfredbrandl** [comment]
Just tried the preview with a german keyboard, '?' does not open keyboard shortcuts. On a german keyboard '?' is shift-'ß' just right of '0'.

**Comment by bhousel** [comment]
Hmm maybe #3572 will work now that Chrome is a few versions further.  cc @tyrasd

**Comment by magol** [comment]
@bhousel 
I have also found out that even following keyboard shortcuts  are not working on a Swedish keyboard:

 - <kbd>/</kbd>  –   Toggle minimap 
 - <kbd>Ctrl+\|</kbd> –  Toggle info/measurements box 
 - <kbd>[</kbd> –  Jump to previous vertex
 - <kbd>]</kbd> –  Jump to next vertex
 - <kbd>Ctrl+[</kbd> –  Jump to first vertex
 - <kbd>Ctrl+]</kbd> –  Jump to last vertex
 - <kbd>\\</kbd> – Cycle through parent ways
 - <kbd>?</kbd> – Show keyboard shortcuts

The problem is that you give this keys on a differently way on a Swedish keyboard then on a US keyboard

| Char | On a US keyboard        | On a Swedish keyboard  | 
| ---- |--------------------------| ---------------------------|
|   `/`   | <kbd>/</kbd>             | <kbd>Shift</kbd>+<kbd>7</kbd> |
| `\`   | <kbd>\\</kbd>             |  <kbd>Alt Gr</kbd>+<kbd>?</kbd> |
| `?`    | <kbd>Shift</kbd>+<kbd>/</kbd>   | <kbd>Shift</kbd>+<kbd>+</kbd> |
|  `\| `  | <kbd>Shift</kbd>+<kbd>\\</kbd> | <kbd>Alt Gr</kbd>+<kbd>\<</kbd> |
| ` ]`    | <kbd>]</kbd>                                    | <kbd>Alt Gr</kbd>+<kbd>9</kbd> |
|  `[ `   | <kbd>[</kbd>                                    | <kbd>Alt Gr</kbd>+<kbd>8</kbd> |

Perhaps we should make it possible to localize the keyboard shortcuts?

Several of the keyboard shortcuts become unnecessary complicated when it require multiple keystrokes on a Swedish keyboard (and probably other keyboards as well).
In addition, the shortcuts based on letters are related to what it is called in English. In other languages, other letters may be more logical.

**Comment by bhousel** [comment]
ok few things:

* We know about <kbd>/</kbd> minimap being an issue
* info box shortcut is <kbd>Ctrl</kbd>+<kbd>i</kbd>  (not "pipe")
* We knew about the vertex navigation shortcuts being an issue, 
which is why we added the <kbd>PgUp</kbd><kbd>PgDn</kbd><kbd>Home</kbd><kbd>End</kbd><kbd>Pause</kbd> alternatives
* I'm not surprised about <kbd>?</kbd> shortcut screen being an issue for the same reasons as <kbd>/</kbd>.  
We only merged this code a few days ago.

(also - which browser/os are you testing with?)

**Comment by bhousel** [comment]
@manfredbrandl said:

> Just tried the preview with a german keyboard, '?' does not open keyboard shortcuts. On a german keyboard '?' is shift-'ß' just right of '0'.

We could _probably_ fix this for German by keybinding <kbd>shift</kbd>+<kbd>ß</kbd> as we don't use <kbd>ß</kbd> for anything.

Swedish I'm less certain specifically because it shares the <kbd>?</kbd> key with <kbd>+</kbd>.

**Comment by bhousel** [comment]
@magol, @manfredbrandl : Can you test these issues again with the latest http://preview.ideditor.com/master ?  When you test, let me know what browser and os you are using too, because that might matter.

I just merged #3572 (thanks @tyrasd!) which gives us a more reliable way to know which key was pressed in modern browsers.

**Comment by magol** [comment]
I tested on a Windows 7 with Chrome 58.0, and it WORKS!!!! :-D

All shortcuts are working now except for <kbd>{</kbd>, <kbd>[</kbd>, <kbd>]</kbd>} and <kbd>\\</kbd>. But for them it is a replacement so it does not matter.

**Comment by manfredbrandl** [comment]
I tested '?' successfully with German Keyboards on Windows 64bit with Chrome 58, Firefox 53 and IE 11 and on Debian Linux 64bit with Firefox ESR 45 and Chromium 57. Midori shows a minimap in the upper left corner of the map, but that's not so important. Also in Servo iD did not work at all (no map), but that's also not so important.

**Comment by manfredbrandl** [comment]
Some keys for browsing don't work on my German Keyboard, but the alternative keys work:
![image](https://cloud.githubusercontent.com/assets/5360273/26828632/af5e2aea-4ac2-11e7-9dfa-9d5d27f008d7.png)

**Comment by magol** [comment]
The common for the shortcuts that still do not work is that everyone uses <kbd>Alt Gr</kbd> on a Swedish keyboard. So it seems that that key is not handled properly.

**Comment by magol** [comment]
I'm missing shortcut for <kbd>Delete</kbd>. When I press that key a feature is removed, but it is not in the list of valid shortcuts.

**Comment by bhousel** [comment]
@manfredbrandl: 
> I tested '?' successfully with German Keyboards on Windows 64bit with Chrome 58, Firefox 53 and IE 11 and on Debian Linux 64bit with Firefox ESR 45 and Chromium 57. Midori shows a minimap in the upper left corner of the map, but that's not so important. Also in Servo iD did not work at all (no map), but that's also not so important.

Great thanks!  That is good news.  We don't support it but I'll install Midori on my Windows machine just for fun.  I'm not surprised that iD doesn't work at all in Servo - I don't think it has SVG support yet.

@magol:
> The common for the shortcuts that still do not work is that everyone uses Alt Gr on a Swedish keyboard. So it seems like that Alt Gr is not handled properly.

Hmm that is interesting.. It's not one of the modifiers we check for, but I would expect the shortcuts to work anyway if we are using [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) now.  I think I can trick my keyboard into sending <kbd>AltGr</kbd> and see what happens.

>I'm missing shortcut for Delete. When I press that key a feature is removed, but it is not in the list of valid shortcuts.

Yes, I didn't have space on the screen to include it without wrapping to another line, but I can try to make the modal a little bit wider.

**Comment by magol** [comment]
The <kbd>Enter</kbd> and <kbd>Esc</kbd> keys is on two lines because the Swedish translation of `-or-` has more letters than in English.

![image](https://user-images.githubusercontent.com/493140/26867085-2d9e5e9c-4b64-11e7-8275-7bed794e7c37.png)

**Comment by magol** [comment]
I'm a little worried that users will miss that it is two separate views to choose from (Browse and Editing). I recommend that you make it graphically clearer that there are two tabs.

**Comment by magol** [comment]
By the way, why is there no way to get this window in any other way than with the <kbd>?</kbd> key? The only place where I have found information about this is far down in an help text. I did not know anything this before, and the risk is high that most users do not know about it. I think there should be a visible button under the help to view this window.

**Comment by bhousel** [comment]
> The Enter and Esc keys is on two lines because the Swedish translation of -or- has more letters than in English.

I think the real reason that the columns are sized that way is because the text for <kbd>Alt</kbd> is too long.  I could fix the widths though, so that if anything is going to wrap it will be the description side.

> I'm a little worried that users will miss that it is two separate views to choose from (Browse and Editing). I recommend that you make it graphically clearer that there are two tabs.

I think it's ok.

> By the way, why is there no way to get this window in any other way than with the ? key? The only place where I have found information about this is far down in an help text. I did not know anything this before, and the risk is high that most users do not know about it. I think there should be a visible button under the help to view this window.

Sure I'll add a button or link to the first page of the help screen.  This feature was just added last week, and iD has existed for many years without it, so I'm not too worried about the risk of users not finding it.

**Comment by bhousel** [comment]
Hey @magol I added an item on the help pane mentioning the keyboard shortcuts, and I increased the width of the popup a bit to accommodate larger texts.

Can you verify these items in http://preview.ideditor.com/master/ 
If you find anything else please open a new issue, thanks!


<img width="300" alt="screenshot 2017-06-08 22 37 25" src="https://user-images.githubusercontent.com/38784/26958925-5086b368-4c9b-11e7-8b3b-b0a67dd9e4eb.png">

**Comment by magol** [comment]
Great

I can't find any translation of "Shot the keyboard shortcuts screen." in Transifex. But it may just be because it has not yet been synchronized there.

The only thing I react to is that the help panel is still displayed in the background when the view of keyboard shortcuts is displayed. When I then choose to change tabs in the view (between `Browsing` and `Editing`), the help will be hidden in the background.

![image](https://user-images.githubusercontent.com/493140/26964095-48970180-4cf0-11e7-890b-7104abdb61d9.png)
