### ISSUE TITLE
Upgrade to id-tagging-schema v3.1.0

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8600]
Translatable labels of fields always show up in English even when a translation is available.

For example, when viewing the Vietnamese localization, the Surface field’s [hard-coded options](https://github.com/openstreetmap/id-tagging-schema/blob/e8d86eb0bdbad8e466a6e06a62899f422440175a/data/fields/surface.json#L6-L19) are all in English, including “Artificial Turf” for `surface=artificial_turf`, even though [the corresponding message in Transifex](https://www.transifex.com/openstreetmap/id-editor/translate/#vi/presets/309271270?q=text%3Aturf) has already been translated. These fields were added in openstreetmap/id-tagging-schema@92ae85603aedfcefeaa4687b039ad54cff40f7b3, which was released as v3.0.0. cb7f1c2b3ca93216df28c7b70a44b5e46f23c9e9 upgraded to v3.0.0.

**Comment by 1ec5** [comment]
Oh, I think the issue is that v2.20.0 didn’t pull the latest translations from Transifex. Only a Transifex project administrator can do that, unfortunately.

**Comment by mbrzakovic** [comment]
It seems you are partially correct. I did run [fresh translations prior to release in iD](https://github.com/openstreetmap/iD/commit/060a73998783b6f7229ba809ed7793ffc35c3bc5)  however it seems that preset translations are [pulled in runtime](https://github.com/openstreetmap/iD/blob/6b1180f1169cb1ad6c03cb19671a086e9af9f54d/modules/core/localizer.js#L93) from id-tagging-schema release. I am looking into this now, if this is the case just updating translations on id-tagging-schema side should resolve this.

**Comment by 1ec5** [comment]
> if this is the case just updating translations on id-tagging-schema side should resolve this

Thanks for doing this in openstreetmap/id-tagging-schema@bde8a416c80cbbb27a0ad36df3c6dcec3151ec8b. It did [add the translations to the id-tagging-schema files](https://github.com/openstreetmap/id-tagging-schema/blob/42d86acc7fa8e8ff01485437889c6784f244dea1/dist/translations/vi.json#L2214). However, ideditor.netlify.app [still isn’t showing the translations](https://ideditor.netlify.app/#background=Mapbox&disable_features=boundaries&id=w168825325&locale=vi&map=20.00/39.28258/-84.28475):

<img width="376" alt="surface" src="https://user-images.githubusercontent.com/1231218/138571958-9d0a11e3-17d3-45c3-af25-35cd62376c0e.png">

This line is returning untranslated strings like “Asphalt”:

https://github.com/openstreetmap/iD/blob/61215456fc9fd54dded0bd0f728c3a0064efad5d/modules/ui/fields/combo.js#L205

**Comment by 1ec5** [comment]
openstreetmap/id-tagging-schema@bde8a416c80cbbb27a0ad36df3c6dcec3151ec8b went into v3.1.0, but [`@openstreetmap/id-tagging-schema`](https://www.npmjs.com/package/@openstreetmap/id-tagging-schema) v3.1.0 hasn’t been released to NPM yet. @quincylvania @bhousel @Firefishy are the maintainers of that package.

**Comment by tyrasd** [comment]
v3.1.0 was finally released a few days ago (see https://www.npmjs.com/package/@openstreetmap/id-tagging-schema?activeTab=versions) and the CDN's cache now has the new version available. It could be that browsers still have the old version cached locally (expiry is set to 7 days AFAICS), but essentially this specific issue should be solved now.

I must say that I don't feel too good about the current setup for releasing the tagging database. Having to "deal" with two layers of caches which are out of our control on top of the existing build pipeline is not really ideal. For example, if at any point a release went wrong, it could take up to two weeks until end users get the fix. :unamused: 

I think the way forward would be to move away from distributing the id-tagging-schema via a npm-based CDN to something else – potentially something self hosted on osm.org.

**Comment by bhousel** [comment]
There is a simple way to purge the JSDelivr CDN cache and I am happy to share it with you.
The JSDelivr folks have asked me not to share it widely, otherwise I would just post it here.
