### ISSUE TITLE
"Backward" and "reverse" shouldn't both be available

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9389]
Just the other day I was tagging some railroad signals  and the prompt system suggested "reverse", so I picked it.

But then I noticed that other people's signals had this nice kind of flashlight effect on them. Oh they had tagged their signals "backward".

I looked in the selection list menu, and lo and behold backward was just a little bit further down than reverse. But that's only on some days.

Anyway you want to get the bad one out and leave the good one in, not let users just accidentally pick the wrong one.

Maybe you are just reflecting what most people type in but there ought to be some guidance of blacklisted words. 

I still haven't checked the wiki to see which one is correct. All I know is if it gets special effects on the map (in iD) and the other one doesn't,  that's the one I'll use. 

Yup, "editing for the (editor) renderer," that's me!

**Comment by tyrasd** [comment]
The direction field for railway signals ([`railway/signal/direction`](https://github.com/openstreetmap/id-tagging-schema/blob/v5.0.1/data/fields/railway/signal/direction.json), which is used by the Railway Signal preset) only has `forward`, ` backward` and `both` as allowed options. Do you mean a different preset perhaps?

**Comment by Dimitar5555** [comment]
He is talking about the suggestions from taginfo which appear in the tag editor. I've already fixed most of the instances of that tag and they shouldn't appear.

**Comment by tyrasd** [comment]
OK. I'm however still wondering which field or preset is affected by this issue. Because the direction field of the "Railway Signal" preset does not trigger a taginfo lookup as far as I can see. I'd be interested in knowing which field might still have this bug.

Or did you got this in the raw tags editor @jidanni?

**Comment by jidanni** [comment]
I apologize that it's hard to explain / remember exactly what happened. And another difficulty is it seems to learn with what one uses  too, so reproducing might be difficult.

So maybe all the places that one might encounter the wrong values have now been plugged up by @Dimitar5555 , so I'll just close this for now. Thanks.
